flags: {}
packages:
- haskoin-core
- haskoin-node
- haskoin-wallet
extra-deps:
- daemons-0.2.1
- murmur3-1.0.2
- pbkdf-1.1.1.1
- secp256k1-0.4.6
nix:
  enable: false
  packages: [ncurses, autoreconfHook, pkgconfig, czmq, zlib]
resolver: lts-6.15
