flags: {}
packages:
- haskoin-core
- haskoin-node
- haskoin-wallet
extra-deps:
- daemons-0.2.1
- esqueleto-2.4.3
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.6
nix:
  enable: false
  shell-file: shell.nix
resolver: lts-6.23
