# ZeroMQ socket on which to listen to. Either absolute path or relative to
# work-dir/network.
bind-socket:       ipc://hw1.sock
bind-socket-notif: ipc://notif1.sock

# ZeroMQ socket to communicate with the server.
# Either absolute path or relative to the server work-dir/network path.
connect-uri:       ipc://hw1.sock
connect-uri-notif: ipc://notif1.sock

# Server mode. Can be either online or offline. In offline mode, the SPV
# daemon does not start and only the local wallet is available to query.
server-mode: online

server-port: 29521

# False positive rate for the bloom filters.
bloom-false-positive: 0.00001

# Database connection information.
database:
    testnet:
        database: hw-wallet1.sqlite3
        poolsize: 1
    prodnet:
        database: hw-wallet1.sqlite3
        poolsize: 1

# List of trusted bitcoin full-nodes to connect to.
bitcoin-full-nodes:
    testnet: []
    prodnet: 
        - host: 127.0.0.1
          port: 29522
        
# Log file name. Either absolute path or relative to work-dir/network
log-file: hw1.log

# PID file name. Either absolute path or relative to work-dir/network.
pid-file: hw1.pid

# Compile time configuration value. Either absolute path or relative to
# work-dir. Can only be set as environment variable.
config-file: config.yml

# Default output size for commands such as page sizes.
output-size: 10

# Type of addresses to display. Example: external, internal
address-type: external

# Use reverse paging for diplaying addresses and txs when set to True.
reverse-paging: false

# Sign new and imported transactions.
sign-transactions: true

# Default fee to pay (in satoshi) for every 1000 bytes.
transaction-fee: 10000

# Minimum number of confirmations for spending coins and displaying balances.
minimum-confirmations: 0

# Display the balance including offline transactions
offline: false

# How command-line output should be displayed. Supported values are:
# normal, json or yaml.
display-format: normal

# Detach the SPV server from the terminal when launched
detach-server: false

# Use Testnet3
use-testnet: false

# Haskoin working directory. Either absolute path or relative to user’s home.
# Defaults to an appropriate OS-specific value.
work-dir: ""

# Log level. Valid values are debug, info, warn and error.
log-level: info

# Print verbose
verbose: false

# Recipient pays transaction fee. DANGEROUS.
recipient-fee: false

# Configuration file name. Only set at compile time.
config-file: config.yml

# Server key for authentication and encryption (server config).
server-key:
# Server public key for authentication and encryption (client config).
server-key-public:

# Client key for authentication and encryption (client config).
client-key:
# Client public key for aunthentication and encryption (client + server config).
client-key-public:
